[package]
name = "shmeatley/atlas"
description = "A procedural generation toolkit for Roblox."
version = "0.1.3"
license = "MIT"
authors = ["shmeatley"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"

exclude = ["**"]
include = [
    "src",
    "src/**",
    "wally.toml",
    "default.project.json"
]
